export default {
  index: 'About Zaunchpad',
  demo: 'Demo',
  architecture: 'Architecture',
  'tee-proof-generator': 'TEE Proof Generator',
  'user-guides': 'User Guides',
  'near-intents': 'Working with NEAR Intents',
  'oft-claiming': 'Claiming with OFT',
  'zcash-pools': 'How Zcash Pools Work',
  'anonymity-set': 'Understanding Anonymity Set',
  'supported-chains': 'Supported Chains',
  'future-features': 'Future Features',
  debugging: 'Debugging',
  faq: 'FAQ',
};
