const SOL_NETWORK = process.env.NEXT_PUBLIC_SOL_NETWORK || '';
const HELIUS_API_KEY = process.env.NEXT_PUBLIC_HELIUS_API_KEY;
const NEAR_NETWORK = process.env.NEXT_PUBLIC_NEAR_NETWORK;
const TATUM_API_KEY =
  NEAR_NETWORK == 'mainnet'
    ? process.env.NEXT_PUBLIC_TATUM_API_KEY_MAINNET
    : process.env.NEXT_PUBLIC_TATUM_API_KEY_TESTNET;
const ONECLICK_JWT_TOKEN = process.env.NEXT_PUBLIC_ONECLICK_JWT || '';
const ONECLICK_API_BASE_URL =
  process.env.NEXT_PUBLIC_ONECLICK_API_BASE_URL || 'https://1click.chaindefuser.com';
const STORACHA_EMAIL = process.env.NEXT_PUBLIC_STORACHA_EMAIL;
const STORACHA_PRIVATE_KEY = process.env.NEXT_PUBLIC_STORACHA_PRIVATE_KEY;
const STORACHA_PROOF = process.env.NEXT_PUBLIC_STORACHA_PROOF;
const STORACHA_SPACE_DID = process.env.NEXT_PUBLIC_STORACHA_SPACE_DID;
const TEE_ENDPOINT = process.env.NEXT_PUBLIC_TEE_ENDPOINT || 'https://66a817b166c0b222ae386af54c178986e90beb0a-3000.dstack-pha-prod7.phala.network';
const DEBRIDGE_DLN_API_BASE = process.env.NEXT_PUBLIC_DEBRIDGE_DLN_API_BASE || 'https://dln.debridge.finance/v1.0';
const DEBRIDGE_STATS_API_BASE = process.env.NEXT_PUBLIC_DEBRIDGE_STATS_API_BASE || 'https://stats-api.dln.trade/api';
const LAUNCH_PROGRAM_ID = process.env.NEXT_PUBLIC_LAUNCH_PROGRAM_ID || '';

export {
  SOL_NETWORK,
  HELIUS_API_KEY,
  NEAR_NETWORK,
  TATUM_API_KEY,
  ONECLICK_JWT_TOKEN,
  ONECLICK_API_BASE_URL,
  STORACHA_EMAIL,
  STORACHA_PRIVATE_KEY,
  STORACHA_PROOF,
  STORACHA_SPACE_DID,
  TEE_ENDPOINT,
  DEBRIDGE_DLN_API_BASE,
  DEBRIDGE_STATS_API_BASE,
  LAUNCH_PROGRAM_ID,
};
