const SOL_NETWORK = process.env.NEXT_PUBLIC_SOL_NETWORK || 'devnet';
const HELIUS_API_KEY = process.env.NEXT_PUBLIC_HELIUS_API_KEY;
const WALLET_CONNECT_PROJECT_ID = process.env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID;
const ALCHEMY_API_KEY = process.env.NEXT_PUBLIC_ALCHEMY_API_KEY;
const NEAR_NETWORK = process.env.NEXT_PUBLIC_NEAR_NETWORK;
const NEAR_WALLET_CONNECT_PROJECT_ID = process.env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID || "dba65fff73650d32ae5157f3492c379e";
const SOL_PRIVATE_KEY = process.env.NEXT_PUBLIC_SOL_PRIVATE_KEY
const EVM_NETWORK = process.env.PNEXT_UBLIC_EVM_NETWORK;
const TATUM_API_KEY = NEAR_NETWORK == "mainnet" ? process.env.NEXT_PUBLIC_TATUM_API_KEY_MAINNET : process.env.NEXT_PUBLIC_TATUM_API_KEY_TESTNET
const ETHERSCAN_API_KEY = process.env.NEXT_PUBLIC_ETHERSCAN_API_KEY
const ONECLICK_JWT_TOKEN = process.env.NEXT_PUBLIC_ONECLICK_JWT || "";
const ONECLICK_API_BASE_URL = process.env.NEXT_PUBLIC_ONECLICK_API_BASE_URL || "https://1click.chaindefuser.com";

export { 
    SOL_NETWORK, 
    HELIUS_API_KEY, 
    WALLET_CONNECT_PROJECT_ID, 
    ALCHEMY_API_KEY,
    NEAR_NETWORK,
    NEAR_WALLET_CONNECT_PROJECT_ID,
    SOL_PRIVATE_KEY,
    EVM_NETWORK,
    TATUM_API_KEY,
    ETHERSCAN_API_KEY,
    ONECLICK_JWT_TOKEN,
    ONECLICK_API_BASE_URL
};